services:
  wg:
    image: linuxserver/wireguard
    container_name: wg
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    ports:
      - 51820:51820/udp
      - 51820:51820/tcp
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1